// 初期サンプルデータ（ユーザーの 2026/6〜2027/1 納税予定）。
// 空の状態のとき「初期データを読み込む」で投入できる。

import { DOC_VERSION, type ScheduleDoc, type ScheduleItem } from '../types';

const SEED_ITEMS: ScheduleItem[] = [
  {
    id: 'seed-residence-1',
    dueDate: '2026-06-28',
    dueApprox: false,
    category: 'residence',
    label: '市民税・県民税 第1期',
    amount: 82500,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '',
  },
  {
    id: 'seed-income-1',
    dueDate: '2026-07-27',
    dueApprox: false,
    category: 'income',
    label: '所得税 予定納税 第1期',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '金額未登録（通知到着後に入力）',
  },
  {
    id: 'seed-business-1',
    dueDate: '2026-08-31',
    dueApprox: true,
    category: 'business',
    label: '個人事業税 第1期',
    amount: 87500,
    amountApprox: true,
    status: 'estimated',
    paid: false,
    paidDate: null,
    note: '8月ごろ・予測額',
  },
  {
    id: 'seed-residence-2',
    dueDate: '2026-08-28',
    dueApprox: false,
    category: 'residence',
    label: '市民税・県民税 第2期',
    amount: 80000,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '',
  },
  {
    id: 'seed-residence-3',
    dueDate: '2026-10-30',
    dueApprox: false,
    category: 'residence',
    label: '市民税・県民税 第3期',
    amount: 80000,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '',
  },
  {
    id: 'seed-business-2',
    dueDate: '2026-11-30',
    dueApprox: true,
    category: 'business',
    label: '個人事業税 第2期',
    amount: 87500,
    amountApprox: true,
    status: 'estimated',
    paid: false,
    paidDate: null,
    note: '11月ごろ・予測額',
  },
  {
    id: 'seed-income-2',
    dueDate: '2026-11-26',
    dueApprox: false,
    category: 'income',
    label: '所得税 予定納税 第2期',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '金額未登録（通知到着後に入力）',
  },
  {
    id: 'seed-residence-4',
    dueDate: '2027-01-29',
    dueApprox: false,
    category: 'residence',
    label: '市民税・県民税 第4期',
    amount: 80000,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '',
  },
  // 固定資産税（第1〜4期）
  {
    id: 'seed-property-1',
    dueDate: '2026-04-30',
    dueApprox: false,
    category: 'property',
    label: '固定資産税 第1期',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '金額未登録（納税通知書到着後に入力）',
  },
  {
    id: 'seed-property-2',
    dueDate: '2026-07-31',
    dueApprox: false,
    category: 'property',
    label: '固定資産税 第2期',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '',
  },
  {
    id: 'seed-property-3',
    dueDate: '2026-12-25',
    dueApprox: false,
    category: 'property',
    label: '固定資産税 第3期',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '',
  },
  {
    id: 'seed-property-4',
    dueDate: '2027-02-26',
    dueApprox: false,
    category: 'property',
    label: '固定資産税 第4期',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '',
  },
  // 自動車税
  {
    id: 'seed-vehicle-1',
    dueDate: '2026-05-31',
    dueApprox: false,
    category: 'vehicle',
    label: '自動車税',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '金額未登録（通知書到着後に入力）',
  },
  // 消費税
  {
    id: 'seed-consumption-1',
    dueDate: '2026-03-31',
    dueApprox: false,
    category: 'consumption',
    label: '消費税 確定申告',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '前年分・金額未登録',
  },
  {
    id: 'seed-consumption-2',
    dueDate: '2026-11-30',
    dueApprox: true,
    category: 'consumption',
    label: '消費税 中間申告',
    amount: null,
    amountApprox: false,
    status: 'estimated',
    paid: false,
    paidDate: null,
    note: '11月ごろ・金額未登録',
  },
  // 源泉所得税（特例）
  {
    id: 'seed-withholding-1',
    dueDate: '2026-07-10',
    dueApprox: false,
    category: 'withholding',
    label: '源泉所得税 上半期（1〜6月分）',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '金額未登録',
  },
  {
    id: 'seed-withholding-2',
    dueDate: '2027-01-20',
    dueApprox: false,
    category: 'withholding',
    label: '源泉所得税 下半期（7〜12月分）',
    amount: null,
    amountApprox: false,
    status: 'confirmed',
    paid: false,
    paidDate: null,
    note: '金額未登録',
  },
];

/** 初期サンプルのドキュメントを新規生成して返す */
export function createSeedDoc(now = new Date()): ScheduleDoc {
  return {
    version: DOC_VERSION,
    updatedAt: now.toISOString(),
    // 参照共有を避けてディープコピー
    items: SEED_ITEMS.map((i) => ({ ...i })),
  };
}
